### ISSUE TITLE
Do you accept contributors?

### ISSUE THREAD

**Issue by MarianoOG** [brunorosilva/todoist-analytics#6]
Hi brunorossilva, 

I have been using Todoist for more than 2 years now, almost every day. And I was planning to develop a similar app like yours to leverage the data that I have been producing. I have several ideas for reports that I would love to see. My intention was also to make it available to everyone as open source. I was really happy to find out that you already got a great deal of what I was planning to do, I will for sure fork your project and continue from there. However, I was wondering if you would consider contributions to your code. 

I am a junior-mid developer but have processed data, used the Todoist API, Heroku, streamlit and several graphical libraries in python in the past. Before starting, I will need to understand more about your code and how you're organizing things (I just found out about it some minutes ago).  This will be a passion project that I will contribute to during my free time. 

Let me know if you're interested. Anyway, thanks for the app.

Best,
Mariano Orozco García.

**Comment by brunorosilva** [comment]
@MarianoOG It'd be my pleasure, open source is all about that. Just let me know what features you'll be developing beforehand just so we can be aligned.

In these last few weeks, unfortunetly, I haven't got the time needed to take good care of this project. But I'm be avaible for code reviewing or to feature discussion at anytime here or via my [other socials](https://rosilva.carrd.co/).

Just be aware that my plan is to port the backend to Flask by end of July and the frontend to Next JS some time around the end of the year, but I'll make sure to create another repo for this and I'll only publish this new version once it's good enough.

**Comment by MarianoOG** [comment]
Perfect, thank you very much, I can help with Flask and I will need to learn about Next JS. I will be reviewing the code this week and let you know in which feature I will be working on next week.
